# Generated by Django 4.1.2 on 2022-10-31 02:45

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('mobile_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('status', models.CharField(choices=[('student', 'student, pursuing degree'), ('teacher', 'teacher, eger to learn'), ('other', 'other, intrested')], default='other', max_length=32)),
                ('suggesion', models.TextField()),
            ],
        ),
    ]
