# Generated by Django 4.1.2 on 2022-10-31 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='mobile_number',
        ),
    ]
