# Generated by Django 4.1.2 on 2022-10-31 05:19

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_contactform_suggesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='mobile_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='suggesion',
            field=models.TextField(),
        ),
    ]
