# Generated by Django 4.1.2 on 2022-10-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_contactform_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.EmailField(default='someone@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='mobile_number',
            field=models.CharField(default='1234567890', max_length=10),
        ),
    ]
