# Generated by Django 4.1.2 on 2022-10-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_contactform_email_alter_contactform_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='suggesion',
            field=models.CharField(max_length=1000),
        ),
    ]
