# Generated by Django 4.1.2 on 2022-11-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_student_crud'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_crud',
            name='address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='student_crud',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student_crud',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
