# Generated by Django 4.1.2 on 2022-11-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='XYZ', max_length=100),
        ),
    ]
