# Generated by Django 4.1.2 on 2022-11-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_student_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=100),
        ),
    ]
