# Generated by Django 4.0.6 on 2022-07-18 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('mobile_no', models.IntegerField(default=1000000000)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fees', models.IntegerField(default=1000)),
                ('description', models.TextField(max_length=1080)),
                ('img', models.CharField(max_length=2080)),
                ('covered_topics', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('Duration', models.IntegerField(default=1)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.guardian')),
            ],
        ),
    ]
