# Generated by Django 4.1.2 on 2022-10-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hackathon_participants',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
