# Generated by Django 4.1.2 on 2022-10-30 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('courseDescription', models.TextField(max_length=1000)),
                ('teacher', models.CharField(max_length=256)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.CharField(max_length=100)),
                ('dayTime', models.CharField(max_length=100)),
                ('isAvailable', models.BooleanField(default=True)),
                ('imgUrl', models.CharField(max_length=1500)),
            ],
        ),
    ]
